#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
BO PROFILE (360-degree taxpayer profile) PDF PARSER
=====================================================
Parses the GST-department "BO Profile" PDF (fixed template, per taxpayer
confirmation). Extraction uses pypdf's default extract_text() -- verified to
produce clean single-line-per-row text for every FY-keyed table in this
report (no -layout mode needed; layout mode actually breaks the row grouping
here because of wrapped column headers).

Returns one dict with:
  demographic         : {...}
  financial_by_fy      : {fy: {...}}                 (Financial Information)
  bifa_by_fy            : {fy: {...}}                 (BIFA Specific Information)
  itc_passed_by_fy      : {fy: {...}}
  itc_received_by_fy    : {fy: {...}}
  ewb_by_fy              : {fy: {...}}
  einv_by_fy             : {fy: {...}}
  refund_by_fy           : {fy: {...}}
  top_beneficiaries       : [ {...} ]                  (Top 10 ITC Passed)
  top_suppliers           : [ {...} ]                  (Top 10 ITC Received)
  related_itc_received    : [ {...} ]                  (fraud-risk: related/cancelled supplier)
  related_itc_passed      : [ {...} ]                  (fraud-risk: related/cancelled recipient)
  drc_payments            : [ {...} ]                  (voluntary payments + demand orders)
  self_gstin, legal_name, trade_name
"""

import re
from pypdf import PdfReader

FY_RE = re.compile(r"^(20\d{2}-\d{2})\s+(.*)$")
GSTIN_RE = re.compile(r"\b\d{2}[A-Z]{5}\d{4}[A-Z]\dZ[A-Z\d]\b")
NUM_RE = re.compile(r"-?[\d,]+\.\d{2}|-?[\d,]+")
DATE_RE = re.compile(r"\b\d{4}-\d{2}-\d{2}\b")

_BOILERPLATE_PAT = re.compile(
    r"^(GSTIN:|TradeName:|LegalName:|Data Refresh Date:|Report generated on:|"
    r"Report generated by:|This is system generated report|Suraj Singh\s*$|"
    r"^Suraj Singh\b)"
)


def _num(s):
    if s is None:
        return 0.0
    s = str(s).replace(",", "").replace("%", "").strip()
    if s in ("", "-", "NA", "None"):
        return 0.0
    try:
        return float(s)
    except ValueError:
        return 0.0


def _extract_text(path):
    reader = PdfReader(path)
    text = "\n".join(page.extract_text() for page in reader.pages)
    return text


def _lines(text):
    return [l for l in text.split("\n")]


def _fy_rows(lines, start_idx, end_idx):
    """Yield (fy, [tokens]) for every line in range that starts with a FY like '2022-23'."""
    for l in lines[start_idx:end_idx]:
        m = FY_RE.match(l.strip())
        if m:
            fy = m.group(1)
            toks = m.group(2).split()
            yield fy, toks


def _norm(s):
    """Whitespace-and-case-normalized text, for tolerant marker matching."""
    return re.sub(r"\s+", " ", (s or "")).strip().lower()


def _section_bounds(lines, start_marker, end_markers):
    """Find (start_idx, end_idx) for a section. FIXED to be more tolerant
    (previous version required an EXACT case-sensitive substring on a SINGLE
    line, which silently returns (None, None) -- and every downstream table
    parse quietly becomes empty -- if the real PDF's text extraction wraps a
    section header across two lines, or capitalizes/spaces it slightly
    differently than assumed). Now tries three ways, in order:
      1. exact substring on a single line (fast path, original behaviour)
      2. case-insensitive / whitespace-normalized substring on a single line
      3. case-insensitive / whitespace-normalized substring across a JOINED
         2-line window (catches a header split across a line break)
    Whichever succeeds first is used. Still returns (None, None) if truly
    not found anywhere -- never guesses a fallback position."""
    # 1. exact (fast path, preserves old behaviour when it already worked)
    for i, l in enumerate(lines):
        if start_marker in l:
            return _end_bound(lines, i, end_markers)
    # 2. normalized single-line
    nm = _norm(start_marker)
    for i, l in enumerate(lines):
        if nm and nm in _norm(l):
            return _end_bound(lines, i, end_markers)
    # 3. normalized 2-line joined window
    for i in range(len(lines) - 1):
        joined = _norm(lines[i] + " " + lines[i + 1])
        if nm and nm in joined:
            return _end_bound(lines, i, end_markers)
    return None, None


def _end_bound(lines, start, end_markers):
    end = len(lines)
    norm_end_markers = [_norm(m) for m in end_markers]
    for j in range(start + 1, len(lines)):
        if any(mk in lines[j] for mk in end_markers):
            end = j
            break
        nl = _norm(lines[j])
        if any(nm and nm in nl for nm in norm_end_markers):
            end = j
            break
    return start, end


def diagnose_bo_profile(path):
    """Diagnostic helper (NOT used by the normal pipeline) -- run this
    directly against a real BO Profile PDF to see exactly which sections
    this parser found vs didn't, and a preview of the text near where each
    missing section's marker should be. Intended for closing out a parsing
    bug report without guessing: run `python3 bo_profile_parser.py --diagnose
    <path>` and paste the output back for a precise fix, rather than a
    speculative one."""
    lines = _lines(_extract_text(path))
    sections = [
        ("Financial Information", "Financial Information All Amounts", ["BIFA Specific Information"]),
        ("BIFA", "BIFA Specific Information All Amounts", ["ITC Passed On All Amounts"]),
        ("ITC Passed On", "ITC Passed On All Amounts", ["ITC Received All Amounts"]),
        ("ITC Received", "ITC Received All Amounts", ["Top 10 Benefciaries", "Top 10 Beneficiaries"]),
        ("Top 10 Beneficiaries", "Top 10 Benefciaries", ["Top 10 Suppliers"]),
        ("Top 10 Beneficiaries (alt spelling)", "Top 10 Beneficiaries", ["Top 10 Suppliers"]),
        ("Top 10 Suppliers", "Top 10 Suppliers", ["EWB Related Information"]),
        ("ITC Received from Related", "ITC Received from Related", ["ITC Passed On to Related"]),
        ("ITC Passed On to Related", "ITC Passed On to Related", ["HSN as per REG01"]),
        ("DRC Payment Information", "DRC Payment Information All Amounts", ["Transfer Information"]),
        ("Appeal Information", "Appeal Information", ["Case Information"]),
    ]
    print(f"Total extracted lines: {len(lines)}\n")
    for label, marker, end_markers in sections:
        s, e = _section_bounds(lines, marker, end_markers)
        if s is None:
            print(f"[NOT FOUND] {label!r} (marker: {marker!r})")
            # show a rough guess: any line containing a distinctive keyword from the marker
            kw = marker.split()[0]
            near = [f"  L{i}: {l!r}" for i, l in enumerate(lines) if kw.lower() in l.lower()][:3]
            if near:
                print("   Lines containing the first keyword:")
                print("\n".join(near))
        else:
            print(f"[FOUND]     {label!r} at lines {s}-{e} ({e-s} lines)")
            print(f"   L{s}: {lines[s]!r}")
            if s + 1 < e:
                print(f"   L{s+1}: {lines[s+1]!r}")
        print()


def parse_demographic(lines):
    d = {}
    fields = [
        "GSTIN", "Legal Name", "Trade Name", "Tax Payer Type", "GSTIN / UIN Status",
        "Jurisdiction (Centre/State)", "Level", "Registration Date", "Registration End Date",
        "Mobile Number", "Email", "Nature of Business", "Constitution of Business",
        "GTI Range", "Tax Payer Category", "Overall Risk Score", "QRMP",
        "Last GSTR3B Filed (YYYYMM)", "Last GSTR1 Filed (YYYYMM)",
        "No.of GSTR3B defaulted", "No.of GSTR1 defaulted", "E-invoice Enablement Status",
    ]
    for l in lines[:60]:
        for f in fields:
            if l.strip().startswith(f) and f not in d:
                val = l.strip()[len(f):].strip()
                if val:
                    d[f] = val
    return d


def parse_financial_info(lines):
    s, e = _section_bounds(lines, "Financial Information All Amounts", ["BIFA Specific Information"])
    if s is None:
        return {}
    out = {}
    for fy, t in _fy_rows(lines, s, e):
        # Turnover, Taxable Turnover, RCM(Inward), ITC Reversal(Export Turnover col missing when 0
        # blank), Total tax liability, Tax paid by ITC, Tax paid in cash, ITC availed,
        # [Cash Util% optional], ITC Util%, Effective Tax Rate%, Liability(cash-util ratio?), Cash
        nums = t
        # Percent-bearing columns make count variable (10-13 tokens); map defensively by count.
        vals = [_num(x) for x in nums]
        out[fy] = dict(raw=nums, turnover=vals[0] if len(vals) > 0 else None,
                       taxable_turnover=vals[1] if len(vals) > 1 else None,
                       total_tax_liability=vals[4] if len(vals) > 4 else None,
                       itc_availed=vals[7] if len(vals) > 7 else None)
    return out


def parse_bifa(lines):
    s, e = _section_bounds(lines, "BIFA Specific Information All Amounts",
                            ["ITC Passed On All Amounts"])
    if s is None:
        return {}
    out = {}
    for fy, t in _fy_rows(lines, s, e):
        vals = [_num(x) for x in t]
        # Known layout (variable length -- TDS/TCS block often blank):
        # [0]Liability-GSTR1 [1]Liability-GSTR3B [2]Diff-Liability
        # [3]ITC-R3B [4]ITC-R2B/R2A [5]Diff-ITC
        # [-3]Supply-GSTR3B(EWB-block) [-2]Liability-EWB.. -- safer to read from the END
        # because the optional TDS/TCS-supply-value column is what varies in the middle.
        # RELAXED (was Bug 3's likely cause): the original threshold silently dropped the
        # ENTIRE row for that FY if fewer than 8 tokens were found -- if the real PDF's
        # extraction produces a genuinely blank/missing optional column (no token at all,
        # rather than a '0.00' placeholder), a real row with e.g. 6-7 tokens was discarded
        # wholesale, leaving bifa_by_fy[fy] undefined and every BIFA comparison silently
        # reading 0. Now: only the first 6 fixed-position fields require a minimum length;
        # the tail (EWB-related) fields degrade to None individually if truly absent,
        # instead of taking down the whole row.
        if len(vals) < 6:
            print(f"[warn] BIFA row for FY {fy} has only {len(vals)} numeric token(s) "
                  f"(need >=6) -- skipping this FY. Raw tokens: {t}")
            continue
        liab_g1, liab_g3b, diff_liab = vals[0], vals[1], vals[2]
        itc_r3b, itc_r2b, diff_itc = vals[3], vals[4], vals[5]
        liab_ewb = vals[-2] if len(vals) >= 8 else None
        diff_ewb = vals[-1] if len(vals) >= 7 else None
        supply_g3b = vals[-4] if len(vals) >= 10 else None
        out[fy] = dict(raw=t, liability_gstr1=liab_g1, liability_gstr3b=liab_g3b,
                        diff_liability=diff_liab, itc_r3b=itc_r3b, itc_r2b_r2a=itc_r2b,
                        diff_itc=diff_itc, supply_as_per_gstr3b=supply_g3b,
                        liability_ewb=liab_ewb, diff_ewb_vs_gstr3b=diff_ewb)
    return out


def parse_fy_simple_table(lines, start_marker, end_markers, field_names):
    s, e = _section_bounds(lines, start_marker, end_markers)
    if s is None:
        return {}
    out = {}
    for fy, t in _fy_rows(lines, s, e):
        vals = [_num(x) for x in t]
        row = {}
        for i, fn in enumerate(field_names):
            row[fn] = vals[i] if i < len(vals) else None
        row["raw"] = t
        out[fy] = row
    return out


def _blob(lines, s, e):
    """Join a section's lines into one whitespace-normalised blob, dropping
    repeated page header/footer boilerplate (which otherwise injects a stray
    'GSTIN: <self-GSTIN>' into the middle of a wrapped multi-line record)."""
    clean = [l.strip() for l in lines[s:e]
             if l.strip() and not _BOILERPLATE_PAT.match(l.strip())]
    return re.sub(r"\s+", " ", " ".join(clean))


TOP_LIST_RE = re.compile(
    r"(?P<gstin>\d{2}[A-Z]{5}\d{4}[A-Z]\dZ[A-Z\d])\s+(?P<name>.*?)\s+"
    r"(?P<regstart>\d{4}-\d{2}-\d{2})\s+(?P<regend>NA|\d{4}-\d{2}-\d{2})\s+"
    r"(?P<status>Active|Cancelled)\s+(?P<risk>[\d.]+)\s+(?P<risklabel>LOW|MEDIUM|HIGH)\s+"
    r"(?P<amt>[\d,]+\.\d{2})"
)


def parse_top_list(lines, start_marker, end_markers):
    """Top-10 Beneficiaries / Suppliers tables: GSTIN TradeName RegStart RegEnd Status Risk ITC.
    Records wrap across 2-3 physical lines (trade name), so parse from the
    boilerplate-stripped blob, not line-by-line."""
    s, e = _section_bounds(lines, start_marker, end_markers)
    if s is None:
        return []
    blob = _blob(lines, s, e)
    out = []
    for m in TOP_LIST_RE.finditer(blob):
        out.append(dict(gstin=m.group("gstin"), name=m.group("name").strip(),
                         reg_start=m.group("regstart"), reg_end=m.group("regend"),
                         status=m.group("status"),
                         risk=f"{m.group('risk')} {m.group('risklabel')}",
                         amount=_num(m.group("amt"))))
    return out


REL_PARTY_RE = re.compile(
    r"(?:(?P<fy>20\d{2}-\d{2})\s+)?(?P<gstin>\d{2}[A-Z]{5}\d{4}[A-Z]\dZ[A-Z\d])\s+"
    r"(?P<name>.*?)\s+(?P<param>Mobile|None|PAN|Email|Address)\s+"
    r"(?P<status>Active|Cancelled)\s+(?P<canceldate>NA|\d{4}-\d{2}-\d{2})\s+"
    r"(?P<orderdate>NA|\d{4}-\d{2}-\d{2})\s+(?P<reason>.*?)\s+"
    r"(?P<after>[\d,]+\.\d{2})\s+(?P<total>[\d,]+\.\d{2})\s+"
    r"(?P<risk>[\d.]+)\s+(?P<risklabel>LOW|MEDIUM|HIGH)"
)


def parse_related_party(lines, start_marker, end_markers):
    """Related/Cancelled-party ITC tables: FY GSTIN Name Related-Param Status CancelDate
    OrderDate Reason ITC-After-Cancel Total-ITC RiskScore. Multi-line wrapped -> blob parse.
    FY is only stamped on the first row of a repeat-counterparty run, so carry it forward."""
    s, e = _section_bounds(lines, start_marker, end_markers)
    if s is None:
        return []
    blob = _blob(lines, s, e)
    out = []
    cur_fy = None
    for m in REL_PARTY_RE.finditer(blob):
        if m.group("fy"):
            cur_fy = m.group("fy")
        out.append(dict(fy=cur_fy, gstin=m.group("gstin"), name=m.group("name").strip(),
                         related_parameter=m.group("param"), status=m.group("status"),
                         cancellation_date=m.group("canceldate"), order_date=m.group("orderdate"),
                         reason=m.group("reason").strip(),
                         itc_after_cancellation=_num(m.group("after")),
                         total_itc=_num(m.group("total")),
                         risk=f"{m.group('risk')} {m.group('risklabel')}"))
    return out


def parse_drc_payments(lines):
    s, e = _section_bounds(lines, "DRC Payment Information All Amounts", ["Transfer Information"])
    if s is None:
        return []
    # Strip boilerplate/header/footer noise, keep the rest as one token stream per logical line.
    clean = []
    for l in lines[s + 1:e]:
        t = l.strip()
        if not t or _BOILERPLATE_PAT.match(t):
            continue
        if t in ("Source ID Transaction", "Description", "Transaction", "Payment",
                  "CGST Tax SGST Tax IGST Tax CESS Other Than Tax"):
            continue
        clean.append(t)
    blob = " ".join(clean)
    blob = re.sub(r"\s+", " ", blob)
    # record = SRCID  <freetext type+description>  DATE  (Paid by Cash|Paid by ITC|Liability)  5 numbers
    rec_re = re.compile(
        r"([A-Z]{2}\d{6,}[A-Za-z0-9]{0,8})\s+(.*?)\s+"
        r"(\d{4}-\d{2}-\d{2})\s+(Paid by Cash|Paid by ITC|Liability)\s+"
        r"(-?[\d,]+\.\d{2})\s+(-?[\d,]+\.\d{2})\s+(-?[\d,]+\.\d{2})\s+(-?[\d,]+\.\d{2})\s+(-?[\d,]+\.\d{2})"
    )
    out = []
    for m in rec_re.finditer(blob):
        src, desc, date, method, cgst, sgst, igst, cess, other = m.groups()
        out.append(dict(source_id=src, description=desc.strip(), date=date, method=method,
                         cgst=_num(cgst), sgst=_num(sgst), igst=_num(igst), cess=_num(cess),
                         other=_num(other),
                         total=_num(cgst) + _num(sgst) + _num(igst) + _num(cess) + _num(other)))
    return out


APPEAL_RE = re.compile(
    r"(?P<fy>20\d{2}-\d{2})\s+(?P<arn>[A-Z0-9]+)\s+(?P<filing_date>\d{4}-\d{2}-\d{2})\s+"
    r"(?P<rest>.*?)(?=\s*20\d{2}-\d{2}\s+[A-Z0-9]+\s+\d{4}-\d{2}-\d{2}|$)"
)

TRANSFER_RE = re.compile(
    r"(?P<date>\d{4}-\d{2}-\d{2})\s+(?P<source_id>[A-Z]{2}\d{6,}[A-Za-z0-9]*)\s+"
    r"(?P<rest>.*?)(?=\s*\d{4}-\d{2}-\d{2}\s+[A-Z]{2}\d{6,}|$)"
)


def parse_appeal_info(lines):
    """Appeal Information section. Real layout: Financial Year, ARN, Case Filing
    Date, Case Status, Case Type, Tax Officer Name, Order Number, Selected
    Declaration -- but only the first few columns are reliably populated in
    practice, so the remainder is kept as one raw 'details' string rather than
    forcing an exact-column split that could silently misattribute text."""
    s, e = _section_bounds(lines, "Appeal Information", ["Case Information"])
    if s is None:
        return []
    blob = _blob(lines, s, e)
    out = []
    for m in APPEAL_RE.finditer(blob):
        out.append(dict(fy=m.group("fy"), arn=m.group("arn"), filing_date=m.group("filing_date"),
                         details=m.group("rest").strip()))
    return out


def parse_case_info(lines):
    """Case Information section (SCN/demand cases). Real file for this
    taxpayer has the header only, no data rows -- returns [] in that case,
    which is a legitimate 'no open SCN cases' state, not a parse failure.
    Kept generic (not hardcoded empty) so a future period with real rows is
    still picked up."""
    s, e = _section_bounds(lines, "Case Information All Amounts",
                            ["DRC Payment Information", "Transfer Information"])
    if s is None:
        return []
    blob = _blob(lines, s, e)
    rec_re = re.compile(
        r"(?P<case_id>[A-Z]{2}\d{6,}[A-Za-z0-9]*)\s+(?P<ref_id>\S+)\s+(?P<action_date>\d{4}-\d{2}-\d{2})\s+"
        r"(?P<rest>.*?)(?=\s*[A-Z]{2}\d{6,}|$)"
    )
    return [dict(case_id=m.group("case_id"), ref_id=m.group("ref_id"),
                 action_date=m.group("action_date"), details=m.group("rest").strip())
            for m in rec_re.finditer(blob)]


def parse_transfer_info(lines):
    """Transfer Information section (inter-module case transfers, e.g.
    Enforcement -> Adjudicating Authority). Confirmed the real PDF prints
    this table's content twice (a page-layout duplication, not two distinct
    events) -- de-duplicated here by (date, source_id, details)."""
    s, e = _section_bounds(lines, "Transfer Information", ["Return Filing Details"])
    if s is None:
        return []
    blob = _blob(lines, s, e)
    seen = set()
    out = []
    for m in TRANSFER_RE.finditer(blob):
        key = (m.group("date"), m.group("source_id"), m.group("rest").strip())
        if key in seen:
            continue
        seen.add(key)
        out.append(dict(date=m.group("date"), source_id=m.group("source_id"),
                         details=m.group("rest").strip()))
    return out


def parse_bo_profile(path):
    text = _extract_text(path)
    lines = _lines(text)

    demo = parse_demographic(lines)
    financial = parse_financial_info(lines)
    bifa = parse_bifa(lines)
    itc_passed = parse_fy_simple_table(
        lines, "ITC Passed On All Amounts", ["ITC Received All Amounts"],
        ["intra_benef", "intra_itc", "inter_benef", "inter_itc", "total_benef", "total_itc"])
    itc_received = parse_fy_simple_table(
        lines, "ITC Received All Amounts", ["Top 10 Benefciaries", "Top 10 Beneficiaries"],
        ["intra_supp", "intra_itc", "inter_supp", "inter_itc", "total_supp", "total_itc"])
    ewb = parse_fy_simple_table(
        lines, "EWB Related Information", ["E-Invoice Related Information"],
        ["inward_supply", "inward_tax", "inward_ewb_count", "outward_supply",
         "outward_tax", "outward_ewb_count", "ratio_in_out"])
    # NOTE: column semantics for the last 4 numeric fields ("Active Assessable Value",
    # "Active Taxes", "Cancelled Assessable Value", "Cancelled Taxes") are AMBIGUOUS --
    # the 2022-23 row's 4th value (2999.86) sits far closer to that year's turnover
    # (2985.56, per Financial Information) than a tax figure would, while the 3rd value
    # (335.21) sits close to that year's total tax liability (334.80). This suggests the
    # PDF's wrapped 2-line header may not align 1:1 with data-column order. Kept as raw
    # generic columns rather than asserting a label that could be wrong -- verify against
    # the source PDF/portal before using these two numbers in any check.
    einv = parse_fy_simple_table(
        lines, "E-Invoice Related Information", ["Refund Details"],
        ["active_count", "cancelled_count", "col3_unconfirmed", "col4_unconfirmed",
         "cancelled_assessable_or_tax_unconfirmed", "col6_unconfirmed"])
    refund = parse_fy_simple_table(
        lines, "Refund Details", ["ITC Received from Related"],
        ["claimed", "rejected", "sanctioned"])

    top_benef = parse_top_list(lines, "Top 10 Benefciaries", ["Top 10 Suppliers"])
    if not top_benef:
        top_benef = parse_top_list(lines, "Top 10 Beneficiaries", ["Top 10 Suppliers"])
    top_supp = parse_top_list(lines, "Top 10 Suppliers", ["EWB Related Information"])

    rel_received = parse_related_party(
        lines, "ITC Received from Related", ["ITC Passed On to Related"])
    rel_passed = parse_related_party(
        lines, "ITC Passed On to Related", ["HSN as per REG01"])

    drc = parse_drc_payments(lines)
    appeals = parse_appeal_info(lines)
    cases = parse_case_info(lines)
    transfers = parse_transfer_info(lines)

    return dict(
        self_gstin=demo.get("GSTIN"), legal_name=demo.get("Legal Name"),
        trade_name=demo.get("Trade Name"), demographic=demo,
        financial_by_fy=financial, bifa_by_fy=bifa,
        itc_passed_by_fy=itc_passed, itc_received_by_fy=itc_received,
        ewb_by_fy=ewb, einv_by_fy=einv, refund_by_fy=refund,
        top_beneficiaries=top_benef, top_suppliers=top_supp,
        related_itc_received=rel_received, related_itc_passed=rel_passed,
        drc_payments=drc, appeals=appeals, cases=cases, transfers=transfers,
    )


if __name__ == "__main__":
    import sys, json
    if len(sys.argv) > 1 and sys.argv[1] == "--diagnose":
        diagnose_bo_profile(sys.argv[2] if len(sys.argv) > 2 else
                             "05AAECM6380J1ZA_BO_Profile_15_06_2026.pdf")
        raise SystemExit(0)
    p = sys.argv[1] if len(sys.argv) > 1 else "05AAECM6380J1ZA_BO_Profile_15_06_2026.pdf"
    r = parse_bo_profile(p)
    print("GSTIN:", r["self_gstin"], "|", r["legal_name"])
    print("\nDemographic keys:", list(r["demographic"].keys())[:8], "...")
    print("\nBIFA FY2022-23:", r["bifa_by_fy"].get("2022-23"))
    print("\nFinancial FY2022-23:", r["financial_by_fy"].get("2022-23"))
    print("\nEWB FY2022-23:", r["ewb_by_fy"].get("2022-23"))
    print("\nE-Inv FY2022-23:", r["einv_by_fy"].get("2022-23"))
    print("\nTop beneficiaries:", len(r["top_beneficiaries"]))
    print("Top suppliers:", len(r["top_suppliers"]))
    print("\nRelated ITC received:", len(r["related_itc_received"]))
    for x in r["related_itc_received"][:3]:
        print(" ", x)
    print("\nRelated ITC passed:", len(r["related_itc_passed"]))
    print("\nDRC payments parsed:", len(r["drc_payments"]))
    for x in r["drc_payments"][:8]:
        print(" ", x)
